"""empty message

Revision ID: 6ba0ce3a945f
Revises: f014167ec41a
Create Date: 2022-10-19 04:09:28.360064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ba0ce3a945f'
down_revision = 'f014167ec41a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_constraint('fk_comment_post_id_post', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_comment_post_id_post'), 'post', ['post_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_comment_post_id_post'), type_='foreignkey')
        batch_op.create_foreign_key('fk_comment_post_id_post', 'post', ['post_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
