"""empty message

Revision ID: f014167ec41a
Revises: 6e38e8eea4fe
Create Date: 2022-10-19 04:08:04.244343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f014167ec41a'
down_revision = '6e38e8eea4fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_constraint('fk_comment_post_id_post', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_comment_post_id_post'), 'post', ['post_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_comment_post_id_post'), type_='foreignkey')
        batch_op.create_foreign_key('fk_comment_post_id_post', 'post', ['post_id'], ['id'])

    # ### end Alembic commands ###
